### ISSUE TITLE
faststream import error

### ISSUE THREAD

**Issue by maymon-max** [taskiq-python/taskiq-faststream#30]
Hi! 
I've got an import exception after updating the faststream package to 0.3.13

```
File "./app/taskiq.py", line 3, in <module>
    from taskiq_faststream import BrokerWrapper, StreamScheduler
  File "./venv/lib/python3.11/site-packages/taskiq_faststream/__init__.py", line 1, in <module>
    from taskiq_faststream.broker import AppWrapper, BrokerWrapper
  File "./venv/lib/python3.11/site-packages/taskiq_faststream/broker.py", line 5, in <module>
    from faststream._compat import TypeAlias, override
ImportError: cannot import name 'TypeAlias' from 'faststream._compat' (./venv/lib/python3.11/site-packages/faststream/_compat.py)
```
**Packages:**
```
taskiq-faststream==0.1.6
faststream==0.3.13
```
